name: Script Validation
on:
  push:
    branches-ignore:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install reapack-index
        run: gem install reapack-index

      - name: Run Metadata Check
        run: reapack-index --check